version: "3.7"
services:
  web:
    image: web
    build:
      context: ./
    networks:
      - webnet
    ports:
      - "19009:9000"
    cap_drop:
      - ALL
    environment:
      - SERVER_DEPLOYMENT_TYPE=test
      - SERVER_LISTEN_PORT=9000
networks:
  webnet:
