version: "3.7"
services:
  web:
    image: web
    build:
      context: ./
    networks:
      - webnet
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /etc/letsencrypt/archive/blog.terminaldweller.com/:/certs/
networks:
  webnet:
