services:
  nginx-crs:
    image: owasp/modsecurity-crs:4.25-nginx-alpine-lts
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - 19010:8443
    restart: unless-stopped
    networks:
      blognet: 172.17.55.10
        ipv4_address: 
    environment:
      - BACKEND="http://blog:9000"
      - PROXY_SSL_CERT=/etc/letsencrypt/live/blog.terminaldweller.com/fullchain.pem
      - PROXY_SSL_CER_KEY=/etc/letsencrypt/live/blog.terminaldweller.com/privkey.pem
      - SSL_PORT=8443
    volumes:
      - ./certs/server.cert:/etc/letsencrypt/live/blog.terminaldweller.com/fullchain.pem:ro
      - ./certs/server.key:/etc/letsencrypt/live/blog.terminaldweller.com/privkey.pem:ro
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    runtime: runsc
  blog:
    image: blog
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    restart: unless-stopped
    networks:
      blognet:
        ipv4_address: 172.17.55.11
      dbnet:
        ipv4_address: 172.17.56.11
    ports:
      - "127.0.0.1:19009:9000"
    cap_drop:
      - ALL
    depends_on:
      - nginx-crs
      - mongo
    secrets:
      - mongo_user
      - mongo_pass
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    read_only: true
    runtime: runsc
  mongo:
    image: mongo:7
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      dbnet:
        ipv4_address: 172.17.56.10
    restart: unless-stopped
    ports:
      - "127.0.0.1:27117:27017"
      - "127.0.0.1:27118:27018"
      - "127.0.0.1:27119:27019"
    # volumes:
    #   - blog-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_pass
    secrets:
      - mongo_user
      - mongo_pass
    security_opt:
      - no-new-privileges
    runtime: runsc
networks:
  blognet:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.55.0/24
  dbnet:
    enable_ipv6: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.56.0/24
# volumes:
#   blog-data:
secrets:
  mongo_user:
    file: ./mongo_secrets/mongo_user
  mongo_pass:
    file: ./mongo_secrets/mongo_pass
